# Generated by Django 4.2.6 on 2023-10-17 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('room_name', models.CharField(max_length=20)),
                ('room_capacity', models.IntegerField()),
                ('room_description', models.TextField()),
                ('room_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('reservation_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('reservation_date', models.DateField()),
                ('reservation_start_time', models.TimeField()),
                ('reservation_end_time', models.TimeField()),
                ('reservation_description', models.TextField()),
                ('reservation_status', models.BooleanField(default=True)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomManage.rooms')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
