# Generated by Django 4.2.6 on 2023-10-20 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('room_name', models.CharField(max_length=20)),
                ('room_capacity', models.IntegerField()),
                ('room_description', models.TextField()),
                ('room_status', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('reservation_date', models.DateField()),
                ('reservation_start_time', models.TimeField()),
                ('reservation_end_time', models.TimeField()),
                ('reservation_description', models.TextField(blank=True, null=True)),
                ('reservation_status', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomreservation.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
        ),
    ]
