# Generated by Django 4.2.6 on 2023-10-31 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomreservation', '0002_room_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='photo',
            new_name='room_pic',
        ),
    ]
