# Generated by Django 4.2.6 on 2023-11-06 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomreservation', '0003_rename_photo_room_room_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='user',
            new_name='account',
        ),
    ]
