# Generated by Django 4.2.6 on 2023-11-06 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomreservation', '0006_reservation_reservation_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_end_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_start_time',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_capacity',
            new_name='capacity',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_pic',
            new_name='pic',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_status',
            new_name='status',
        ),
    ]
