# Generated by Django 4.2.6 on 2023-11-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomreservation', '0007_rename_reservation_date_reservation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
