# Generated by Django 4.2.7 on 2023-11-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('account_sid', models.CharField(max_length=100)),
                ('auth_token', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('selected', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
