# Generated by Django 4.2.6 on 2023-10-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_sid', models.CharField(max_length=100)),
                ('auth_token', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
