# Generated by Django 4.2.6 on 2023-10-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twiliosms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twilioaccount',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
